spring:
  application:
    name: base_spring_boot
  datasource:
    url: jdbc:mysql://localhost:3306/base_core?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: haducluongdz@gmail.com
    password: aume ivhz yfee mnnp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
paypal:
  client-id: AS00QCzm53q8t3-Rgod_RR-3RAsAMky4RKOWKdyCEpAtfzStExX483Ypy7LYQgwkXhDfb43KyLtx3BNe
  client-secret: EKfoA6t0ZhDpTLGdUbYnMO3hs87YL0dvppn1vyRZRBP6xIEmSFB3tvrxQICUiZF-tAXckfyOs0-TjFFi
  base-url: https://api-m.sandbox.paypal.com
  return-url: http://localhost:8080/api/paypal/success
  cancel-url: http://localhost:8080/api/paypal/cancel
jwt:
  secret:
    key: Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad
  expired:
    access: 86400
